### ISSUE TITLE
Peer-to-Peer Code Review

### ISSUE THREAD

**Issue by mariosknl** [mariosknl/Platform_Game_Javascript#4]

**Comment by frankopkusianwar** [comment]
Congrats Marios! it is a nice project

**Comment by teekaytech** [comment]
Congratulations Marios. Just as a suggestion, it will be much appreciated if the game can cover the whole browser. I mean, It's nothing but, someone like me finds the white spaces around the game to be distracting. 

Once again, I love the game. 
Nice one :champagne:

**Comment by mbabaliiryn** [comment]
Great work Marios. I love the logic.
